// Discovery unknowns D1–D59 as structured engine data.
// Generated from docs/UNKNOWN_MAP.md — the doc is the source of truth;
// this file is the machine-readable projection the engine reasons over.
// Regenerate (don't hand-edit) if the map changes.

export type UnknownState = "unknown" | "supported" | "hypothesized";

export interface DiscoveryUnknown {
  id: string;
  question: string;
  state: UnknownState;
  stateNote: string;
  cheapestTest: string;
  stakes: string;
  round: number;
}

export const discoveryUnknowns: DiscoveryUnknown[] = [
  {
    id: "D1",
    question: "The \"missing middle\" gap cost — what does \"too busy to answer, not busy enough to hire\" cost a shop per month?",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "\"How many inquiries did you miss last month because you couldn't respond in time?\"",
    stakes: "Sizes a pay-per-recovered-job model vs. per-seat",
    round: 1,
  },
  {
    id: "D2",
    question: "Do owners want to be \"found\"? — fulfillment/admin may bind harder than demand. **Thesis-threatening:** if presence is the constraint, the \"find real opportunities\" wedge needs revision",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "\"If I brought you 10 new customers tomorrow, what breaks?\" — ask first in every discovery conversation",
    stakes: "Could revise the wedge thesis before any build",
    round: 1,
  },
  {
    id: "D3",
    question: "Trust-graph traversal vs. marketing — do first customers come only via pre-existing trust?",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "\"How did your first 10 customers find you?\" — count trust-traced ones",
    stakes: "Hami's RELATION primitive could be the data model",
    round: 1,
  },
  {
    id: "D4",
    question: "The unguarded surfaces map — where do Nepali kirana owners talk with the camera off?",
    state: "unknown",
    stateNote: "UNKNOWN — partial map (research, 2026-10-04): broadcast layer visible (TikTok descriptions/bios/stats, public FB page presence); conversational layer walled (comment text never renders, FB/IG hard 403). Actual talk happens on TikTok/FB/WhatsApp",
    cheapestTest: "Ask owners directly + one Nepali-language TikTok/FB session by a human",
    stakes: "Finds where listening is even possible",
    round: 1,
  },
  {
    id: "D5",
    question: "The unpredictability tax, quantified — hours/week of presence-demanding chaos",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "\"Walk me through last Tuesday.\"",
    stakes: "Turns anecdote into a measurable cost",
    round: 1,
  },
  {
    id: "D6",
    question: "Accountant-as-translator: human or machine? — does the trust require a human neck to wring?",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "\"Would you trust a tool that tells you what the accountant would say?\" — listen for the flinch",
    stakes: "Decides whether this is automatable at all",
    round: 1,
  },
  {
    id: "D7",
    question: "Trust-capital stratification — is who gets to start a birth lottery? (family abroad = payments + credit + hiring)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "~10 owners with/without abroad connections, compare capital sources",
    stakes: "Unmeasured; changes who Hami can serve",
    round: 1,
  },
  {
    id: "D8",
    question: "Returnee-skill pathway — any working path from foreign-earned skills to businesses, or all dissipation?",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "3 returnees who started vs. 3 who didn't",
    stakes: "May resolve BLOCKED_BY_MISSING_ACCESS",
    round: 1,
  },
  {
    id: "D9",
    question: "The voiceless-founder population — how many never surface for lack of network?",
    state: "unknown",
    stateNote: "UNKNOWN (likely BLOCKED_BY_MISSING_ACCESS for direct contact)",
    cheapestTest: "\"Who do you know who wanted to start but didn't, and why?\"",
    stakes: "Measures the invisible demand",
    round: 1,
  },
  {
    id: "D10",
    question: "Reputation vs. paid acquisition by category — which categories run on reputation, and do owners know their game?",
    state: "unknown",
    stateNote: "UNKNOWN (unmapped in Nepal)",
    cheapestTest: "\"Where do your customers come from, honestly?\" — category by category",
    stakes: "Prevents selling funnels to reputation games",
    round: 1,
  },
  {
    id: "D11",
    question: "Rent-vs-presence split by segment — which merchant classes bind on demand (shutter-density retail) vs. presence (social sellers)?",
    state: "unknown",
    stateNote: "UNKNOWN (tension observed 2026-10-04: press says density binds; two Nepali case studies say presence binds)",
    cheapestTest: "In the five conversations, stratify by channel; ask \"which bill scares you most?\" + \"what breaks with 10 new customers?\"",
    stakes: "Decides whether Hami's wedge is demand or response-capacity, per segment — the wedge can't be one thing for both",
    round: 2,
  },
  {
    id: "D12",
    question: "Reply-latency revenue leak on social commerce — how many inquiries die unanswered per week?",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "5 consenting sellers, 1 week of inquiry-vs-reply timestamp logging (Nepali-speaking human, pure observation); or 1 merchant's 7-day tally of calls/WhatsApps received vs answered vs converted",
    stakes: "Decides \"find opportunities\" vs \"catch what you're already dropping\" — Kitab Kiro's own \"can't keep up\" points at the latter",
    round: 2,
  },
  {
    id: "D13",
    question: "Where does the sale actually close — comment, DM, WhatsApp, or voice call?",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "In the five conversations: \"walk me through your last 5 sales, step by step — how did each one actually close?\"",
    stakes: "If voice is the closer, any text assistant is a bridge not a destination — Hami hands off to calls, not replaces them",
    round: 2,
  },
  {
    id: "D14",
    question: "What do informal merchants actually use to accept digital money — personal QR (illegal) or formalization just for payments?",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Sample public Nepali creator walkthroughs (\"पसलमा QR कसरी राख्ने\") + grievance portals for personal-QR-for-business mentions; observation only",
    stakes: "Decides whether the pilot merchant persona is papered or unpapered — which determines whether any QR-based wedge is even legal for them",
    round: 2,
  },
  {
    id: "D15",
    question: "Sub-merchant/aggregator tier: is a legal informal-merchant tier coming (India's UPI P2PM equivalent), or is the paperwork wall structural?",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Read NRB Payment System Department unified directives for \"sub-merchant\"/\"agent aggregator\" language; track Fonepay/eSewa public roadmap (eSewa hints sub-merchant support coming)",
    stakes: "Redraws Hami's entire merchant-addressable map — a legal tier bridges the wall without each kirana getting PAN",
    round: 2,
  },
  {
    id: "D16",
    question: "Is the E-Commerce Act 2025 pushing micro-sellers off formal surfaces onto informal ones?",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Quarterly: Daraz's claimed seller count (press/interviews) vs HamroBazaar active listing volume vs TikTok-seller caption density; watch for enforcement-action press",
    stakes: "If formalization fragments the seller base toward informal surfaces, the wedge targets the informal surface — where the \"one real channel\" actually lives",
    round: 2,
  },
  {
    id: "D17",
    question: "The price-withholding funnel — do Nepali sellers omit prices to force \"inbox\" comments, and does it convert?",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Manual audit of 50 posts across 10 seller pages (price present/absent, comment counts) + ask 3 sellers about conversion; no scraping, no accounts",
    stakes: "If withholding is deliberate lead-capture, Hami \"helping\" via price transparency would fight the seller's own strategy — work with the funnel, not against it",
    round: 2,
  },
  {
    id: "D18",
    question: "Settlement delays: T+1 bank failures or wallet→bank transfer friction — and do they push merchants back to cash?",
    state: "unknown",
    stateNote: "UNKNOWN (45% of semi-urban merchants report delays — NEPJOL 2026; cause unmapped)",
    cheapestTest: "Cross-read NRB monthly payment indicators against delay reports; mine Fonepay Business/eSewa Play Store reviews for \"settlement\" complaints; one shopkeeper narrates one failure end-to-end",
    stakes: "If failures are behavioral, payment confirmation becomes first-class in Hami's evidence layer (receipt-level truth, not policy-level truth); if not, deprioritize entirely",
    round: 2,
  },
  {
    id: "D19",
    question: "Fake-confirmation scams: how often do Kathmandu merchants get shown fake \"Success\" screens, and what is the coping check? (round 3: @thepaisamaster warns पसलहरू against the QR scam; cyber-fraud coverage lists fake QR/eSewa/Khalti screens as common cases)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "In the five conversations: \"Has anyone ever shown you a fake payment screen? What do you check before handing over the goods?\"",
    stakes: "If merchants need adversarial-proof receipt confirmation, Hami's EVIDENCE layer must treat \"paid\" as receipt-level truth on the merchant's own device — and any verification aid must survive a fake green tick",
    round: 3,
  },
  {
    id: "D20",
    question: "Multi-person counter: who at the shop checks QR payments, how do they share visibility without sharing credentials? (round 3: FoneBiz 2.73/5 from 1,917 ratings, 610k downloads; two named shop owners say the post-update single-session model broke their staff-checking workflow)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Ask: \"Who checks the phone when a QR payment comes in — and do they all use the same login?\"",
    stakes: "The merchant persona isn't the owner alone; staff at the counter are presence-constrained workers too — changes who the verification feature is designed for",
    round: 3,
  },
  {
    id: "D21",
    question: "Does the dominant merchant QR app's 2.73 rating push merchants toward cash or personal-QR workarounds?",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Ask: \"Which app do you actually use to confirm QR payments, and why?\" + track FoneBiz rating over quarters",
    stakes: "If the formal rail is unusable at the counter, D14 (informal QR use) gets answered behaviorally — merchants vote with their devices",
    round: 3,
  },
  {
    id: "D22",
    question: "What does a Kathmandu kirana actually net per month — cash taken home, not turnover? (round 4: TikTok business-for-sale listings give turnover+rent for ~6 shops: 10–30k/day, rents 12–32.5k/mo; Samriddhi study: ~5% net on 20 lakh/yr → ~8.3k/mo)",
    state: "unknown",
    stateNote: "UNKNOWN (turnover OBSERVED from listings; margin INFERRED)",
    cheapestTest: "In the five conversations: \"After rent, stock, and the month's udharo that never came back — what lands in your pocket in a normal month?\"",
    stakes: "Sizes the merchant's wallet — a kirana netting ~20k/mo cannot buy per-seat tools; any wedge value capture must be outcome-based and tiny, or monetize elsewhere",
    round: 4,
  },
  {
    id: "D23",
    question: "Does formal supply-side credit (Unilever Shikhar app / channel financing with banks) actually reach small independent kirana, or stop at papered dealers/distributors? (round 4: Unilever Nepal extends credit + training + channel financing; Samriddhi shop advised by landlord *not* to register)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Ask distributors' route salesmen (observation) + ask 3 papered vs 3 unpapered shops: \"Do you get stock on credit from your supplier? From whom, on what terms?\"",
    stakes: "If formal channel credit stops at the paperwork wall, D14's papered/unpapered persona split is confirmed on the supply side too — cash-for-stock is the norm for the informal majority",
    round: 4,
  },
  {
    id: "D24",
    question: "Udharo out vs. udharo in — do shops that extend customer credit also get stock credit from suppliers, and which side breaks first? (round 4: Chamber of Commerce drafted a Commercial Credit Recovery Bill — recovery committees, fast-track courts, bad-debt tax deduction; @pasal.sathi: \"the day you ask for the money, the relationship changes\")",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "In the five conversations: \"Who owes you money right now? And who do you owe?\" — map both ledgers",
    stakes: "If the shop is squeezed on both sides (trust-based udharo out, cash-only stock in), the binding constraint is cash float — not presence, not demand",
    round: 4,
  },
  {
    id: "D25",
    question: "Did Nepal's own ledger apps (\"मेरो कारोबार\", Mero Karobar — Nepali-language khata app, 2020, Gotagaun/Morang, offline+online, NPR 1–2k/yr) survive/scale?",
    state: "supported",
    stateNote: "SUPPORTED (research, 2026-10-04): rebranded to \"Karobar\" ~2022; 500,000+ Play installs (androidrank 2026-09-13, est. ~825k, 3,830 ratings @ 4.43, still growing); founder claims 300k Nepal + 50k Bangladesh downloads, >Rs 10M/yr revenue, 35 employees (New Business Age Sep 2026); Bangladesh traction confirmed by a BRAC University internship report interviewing a Dhaka shop owner user",
    cheapestTest: "",
    stakes: "Don't rebuild it — the udharo-ledger corner is taken by a profitable 35-person Nepali company. Its feature list (record/inventory/invoice) defines the open wedge: money-trust and response-capacity.",
    round: 4,
  },
  {
    id: "D31",
    question: "What is Karobar's actual paying-user conversion and ARPU? (founder claims 300k Nepal + 50k Bangladesh downloads, >Rs 10M/yr revenue; launch pricing Rs 1,000/6mo, Rs 2,000/yr — current pricing unverified)",
    state: "unknown",
    stateNote: "UNKNOWN (rough INFERENCE only: ~low-thousands paying users at Rs 2k/yr ⇒ <2% conversion, or higher ARPU tiers)",
    cheapestTest: "Play Store current pricing tiers + subscription upsell flow; ask 3 paying users what plan they're on",
    stakes: "Sizes the real price ceiling for Nepali merchant software — the first proven in-market number",
    round: 6,
  },
  {
    id: "D32",
    question: "What does Karobar still NOT do that merchants need? (feature list: bookkeeping, inventory, invoicing, payment reminders, multi-staff — no payment rail, no receipt verification, no inquiry handling, no demand)",
    state: "unknown",
    stateNote: "UNKNOWN (surface mapped from Play listing, not merchant testimony)",
    cheapestTest: "In the five conversations: ask Karobar users \"what do you still do outside the app?\" — especially the payment-verification moment (D19) and reply-latency handling (D12)",
    stakes: "The ledger's blind spots are the candidate wedge; confirm them in real voices before building near them",
    round: 6,
  },
  {
    id: "D33",
    question: "Is the Bangladesh expansion organic pull or marketing push? (one Dhaka user interview in a BRAC report + founder claim of ~50k BD downloads + Bangla language support)",
    state: "unknown",
    stateNote: "UNKNOWN (single academic interview ≠ user base)",
    cheapestTest: "Watch for Bangladeshi press/creator mentions; check Play review language mix over quarters",
    stakes: "If the udharo-ledger travels on language support alone, Hami's Nepali-origin tooling has a regional thesis; if it's a press spike, discount it",
    round: 6,
  },
  {
    id: "D34",
    question: "Why did the free Indian khata giants fail to monetize while Karobar charges from day one? (Khatabook: $186.5M raised, 50M+ downloads, FY25 revenue only ₹1.4 Cr, no funding since 2021; Karobar: Rs 10M+/yr, no reported external funding)",
    state: "hypothesized",
    stateNote: "HYPOTHESIZED (2026-10-04): localization (Bikram Sambat calendar) + subscription-from-day-one selection vs free-tier scale play",
    cheapestTest: "Compare churn/retention signals across the apps' review histories; read Khatabook's FY23–FY25 filings if public",
    stakes: "Tests whether \"small, paid, local\" beats \"big, free, foreign\" in merchant software — a pricing thesis for Hami's own first rupee",
    round: 6,
  },
  {
    id: "D26",
    question: "How liquid is the kirana resale market, and do sellers exit on economics (thin margins) or time (busyness)? (round 4: one Chabahil listing explicitly says selling \"व्यस्तताको कारणले\" — because of busyness)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Track sewamandufree listings over quarters (asking price vs. daily sales ratios, time-to-sold) + ask 2 sellers why they sold",
    stakes: "If exit is time-driven, it corroborates D2 (presence binds) from the *seller* side — the shop itself is worth more to a new pair of hands than to the owner",
    round: 4,
  },
  {
    id: "D27",
    question: "The repair-trade survival paradox: is the \"20% net, 80% close within 2 years\" claim real on the ground, and is cash-flow (rent + parts stock) the actual killer? (round 5: Kathmandu repair-training institute page; highest-margin trade studied, least survivable)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "In the five conversations, include 2 repair-bench owners; ask \"what killed the shop that was here before you?\" + observe shutter lineage in one repair lane",
    stakes: "If margin ≠ survival holds, the wedge can't be margin-based pricing at all — outcome/cash-flow framing only",
    round: 5,
  },
  {
    id: "D28",
    question: "Grey parts channel: what share of repair parts move through customs-evading routes, and does that block formal supply credit for the trade entirely? (round 5: Nepal Police seized mobile parts worth NPR 1.15 crore in Parasi, Sep 2026; mobile federation names illegal import as the sector's #1 problem)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Ask 3 repair owners where they source screens/batteries and what happens when a batch is seized or stuck; cross-check with parts wholesalers' public listings",
    stakes: "If the paper trail breaks upstream, formal supply credit (D23) is structurally unavailable to this trade regardless of shop-level paperwork",
    round: 5,
  },
  {
    id: "D29",
    question: "Hands-bound skill monopoly: can repair-bench owners delegate the actual repair, or is the trade strictly one body? (round 5: Dadeldhura owner replies to a \"hire a helper\" comment that he *is* the helper)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Ask repair owners: \"who else in this lane can do what you do, and what would you pay them?\" + ask \"what happens to the shop the week you're sick?\"",
    stakes: "Strictest possible D2: if the repair cannot be delegated, any capacity tool must amplify the owner's own hands — not redistribute work",
    round: 5,
  },
  {
    id: "D30",
    question: "Hands-bound trust: how do customers pick a repair shop (recommendation vs. proximity), and what does the shop do to be worthy of an unlocked device? (round 5: repair promos on FB center on \"विश्वास, गुणस्तर र सेवा\" — trust, quality, service)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "In the five conversations: \"when you handed a stranger your broken phone, why that shop?\" — from both sides of the counter if possible",
    stakes: "If choice is trust-traced (D3 family), the RELATION primitive gets a concrete first use-case: trust-graph traversal for the bench",
    round: 5,
  },
  {
    id: "D35",
    question: "Did the Patan High Court-ordered ride-sharing regulation ever get written? (round 7: 2019 court ordered government to regulate Tootle/Pathao; 2020 DoTM notices still cited the 1993 Act)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Read the current Motor Vehicles and Transport Management Act / ride-sharing guidelines (if any exist) as of 2026; check whether Pathao/InDrive operate under a specific license or continued gray area",
    stakes: "If the regulation never materialized, the \"regulatory space\" Tootle fought for was vapor — pioneers can win the court order and still lose the market",
    round: 7,
  },
  {
    id: "D36",
    question: "What did Tootle's end actually cost — the Rs 34M tax demand, the bans, the founder dispute — and did any investor capital return?",
    state: "unknown",
    stateNote: "UNKNOWN (founder arrested Jan 2024 over ownership-transfer dispute; financial terms of Zapp brand transfer unknown)",
    cheapestTest: "Court/filing records if accessible; Bhatta or Zapp-side accounts; watch the criminal case outcome",
    stakes: "Names the real tail risk for Nepali startups: cap-table disputes can become criminal cases — Hami's own founder/partner agreements need this priced in",
    round: 7,
  },
  {
    id: "D37",
    question: "Why did Pathao's diversification (cars, food delivery) work where Tootle stayed bike-only? Capital alone, or a different theory of the market?",
    state: "hypothesized",
    stateNote: "HYPOTHESIZED (2026-10-04): funded multi-service playbook beat the local single-service purist — Tootle Cabby launched early 2020, too late",
    cheapestTest: "Compare Pathao Nepal revenue mix (press/interviews) vs Tootle's unit economics at shutdown; founder-side accounts",
    stakes: "If multi-service is a survival requirement for Nepali platforms, any single-wedge product (including Hami's) needs the second act planned from day one",
    round: 7,
  },
  {
    id: "D38",
    question: "Is Tootle's double-bind — declared illegal by one agency, taxed by another, defined by neither — a general Nepali pattern?",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Survey other Nepali startups/founders' accounts for \"taxed but not legalized\" cases (e.g., early eSewa/Khalti years, social-commerce sellers under the E-Commerce Act)",
    stakes: "If structural, Hami's risk ledger must treat \"operating in an undefined category\" as simultaneously a tax exposure and an illegality exposure — not one or the other",
    round: 7,
  },
  {
    id: "D39",
    question: "How do merchants finance the Dashain stock-up — supplier credit, savings, or borrowing — and what happens to unsold festival stock when a shock kills the season? (round 8: 2026's Gen-Z-protest shock cut Dashain sales 40–45% vs last year; merchants pre-commit cash to inventory months ahead; ~30–35% of annual consumption in ~2 months)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "In the five conversations: \"What did you buy for Dashain in advance, and if the customers don't come, who eats that stock?\" — plus ask wholesalers about post-season return terms",
    stakes: "Reveals the merchant's real annual risk posture: pre-commitment + concentrated exposure is the business model, and no round has asked who absorbs the miss",
    round: 8,
  },
  {
    id: "D40",
    question: "Does the Dashain cash pulse (NRB: ~Rs 76B leaves banks; cash circulation 6.20T → 6.96T) displace QR/digital payments at the counter — is festival season the worst quarter for digital payment adoption at the merchant counter?",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Cross-read NRB monthly digital-payment indicators for the Dashain months (Asoj–Kartik) vs. adjacent months, 3+ years",
    stakes: "If the cash flood reverses digitalization seasonally, a QR-based wedge must be designed to survive (and not depend on) the annual cash deluge",
    round: 8,
  },
  {
    id: "D41",
    question: "Who bears unsold-stock risk in the wholesale-retail chain when a season fails — the retailer or the distributor? (round 8: Himalayan crossings — Rasuwagadhi halted, Tatopani shut, Korala clearing 2–3 cargo vehicles/day — strand festival inventory upstream)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Ask 3 retailers + 2 wholesalers: \"After a bad Dashain, what happens to the stock that didn't move — returns, discounts, or your loss?\"",
    stakes: "Determines whether the retailer truly pre-commits capital or has an implicit option — changes the economics of any demand-creation wedge",
    round: 8,
  },
  {
    id: "D42",
    question: "Is the dhukuti (rotating savings circle) still the household's festival-credit rail, or have bank loans and digital credit displaced it? (round 8: kharchapatra Sept 2026 prices a Rs 1 lakh Dashain borrow across loan vs credit card vs dhukuti; Labour Act 2074 Sec 37 festival bonus is one month's basic salary — small vs festival spend)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Ask owners directly: \"When Dashain costs more than the bonus, where does the extra come from?\" + watch for dhukuti mentions in Nepali press/creator content",
    stakes: "Maps the fourth credit layer (under udharo-out / supplier-credit / bank-microfinance) — the household's own rotating savings — and whether formalization is reaching it",
    round: 8,
  },
  {
    id: "D43",
    question: "Do unpapered merchants actually borrow from savings-and-credit cooperatives for stock, and at what terms in practice? (round 9: co-ops lend Rs 5–30k for \"starting small shop\" per Sirjana Women SACC, microenterprise Rs 150–300k / SME Rs 200–500k at 16% per Sampanna, Kathmandu slum SACCs charging 18% at 100% recovery; membership-by-share-capital substitutes for bank paperwork)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "In the five conversations: \"When the shop needs money for stock, do you go to the bank, the सहकारी, or someone's door?\"",
    stakes: "Determines whether the cooperative is the merchant persona's real financial institution — which decides whether Hami's finance wedge lives above or outside the sahakari",
    round: 9,
  },
  {
    id: "D44",
    question: "Did the cooperative fraud wave (parliamentary probe 2024: ~Rs 87.89B across 40+ co-ops; ~76,000 depositors owed ~Rs 46B) push merchants back to cash-hoarding/dhukuti or into banks — and what replaces the सहकारी as the merchant float?",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "In the five conversations: \"After the co-op scandals, where do you keep the savings now?\" + watch for co-op mentions in owner-voice content",
    stakes: "If the fraud burned the paperless segment's money-home, merchant finance is in a gap moment — trust in *institutions* is the unknown, not just trust in tools",
    round: 9,
  },
  {
    id: "D45",
    question: "Will NRB's new cooperative directive (Jan 2026 draft: deposits ≤15x primary capital, per-member caps Rs 1M/2.5M/5M, source-of-funds disclosure >Rs 1M) shrink credit availability for small merchants, or only discipline the fraud-prone large co-ops?",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Track NCRA registration compliance (only 18,899 of 32,965 co-ops in COPOMIS; S&C co-ops \"reluctant to register\" per aarthiknews Feb 2026) + ask co-op managers if lending terms tightened",
    stakes: "Decides whether the formalizing-of-trust (N4) closes the easy-loan door for the very merchants who need it — the wedge can't assume the sahakari stays as it was",
    round: 9,
  },
  {
    id: "D46",
    question: "What share of Nepal's ~30,000+ registered cooperatives are active and compliant vs. shells/ghosts — and how can a merchant tell the difference? (round 9: huge registration count, low COPOMIS integration, fake audits found in the fraud probe)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Watch NCRA enforcement reports for de-registration counts; ask owners: \"do you know if your सहकारी is registered with the new authority?\"",
    stakes: "If the sector is padded with shells, \"member-based\" stops meaning safe — and any Hami interaction with cooperative infrastructure needs a legitimacy check first",
    round: 9,
  },
  {
    id: "D47",
    question: "Is IME Group's Sastodeal relaunch actually live and transacting as of 2026, or a parked brand? (round 10: bought 70% Jul 2024 from Dolma's 60% stake at reportedly Rs 30cr, founder kept 10%; relaunch promised)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Check sastodeal.com live + Play Store reviews/traffic signals",
    stakes: "Decides whether conglomerate-rescue of a dead platform works, or is just asset-parking",
    round: 10,
  },
  {
    id: "D48",
    question: "What share of Daraz Nepal sellers are profitable vs. running the platform for inventory movement/cash flow? (round 10: 2026 seller analysis claims stacked platform fees — commission, returns, failed-delivery, vouchers, SLA penalties — can exceed the seller's own product margin)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Ask 5 sellers for one product's unit economics; cross-read seller complaints",
    stakes: "If sellers are a churning conveyor rather than a stable base, any marketplace-dependent wedge is built on sand",
    round: 10,
  },
  {
    id: "D49",
    question: "Gyapu under BG Holdings — alive, parked, or wound down? Does a zero-commission promise survive a conglomerate acquisition? (round 10: acquired Oct 2022 at ~700 orders/day, 3,500 vendors, zero commission + free Valley delivery; founder exited; now quiet)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Check gyapu.com live; vendor-listing freshness",
    stakes: "Tests whether the \"honest brokerage\" playbook is even acquirable in Nepal — or whether every buyer kills it",
    round: 10,
  },
  {
    id: "D50",
    question: "Does the Sept 2026 skill-development-fee procedure (monthly statements even with zero transactions, stamped challans for gold movement, PAN'd craftsmen, customer ID + proof-of-purchase on old-gold buys) push small jewelers toward consolidation or toward non-invoiced dealing? (round 11)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Watch Fenegosida reports for member closures; ask 3 small jewelers: \"do you invoice every sale?\"",
    stakes: "The formalization wave (N2) is live at the highest-value counter — whether paperwork grows the formal sector or the shadow one is the D15/D46 question answered in real time",
    round: 11,
  },
  {
    id: "D51",
    question: "Buyback economics of the two-way counter: what margin does a sunchaandi shop make on new sales vs. the old-gold buyback spread? Is the pawn function the actual profit engine, not the sale? (round 11: \"buy when they have money, sell when they need cash — generations\")",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "In the five conversations, include 1 jeweler; ask: \"which side of the counter pays the rent — the selling or the buying?\"",
    stakes: "If the buyback spread is the engine, the shop is a liquidity provider first and a retailer second — a different business than its storefront suggests",
    round: 11,
  },
  {
    id: "D52",
    question: "What share of a small jeweler's raw material arrives through unofficial channels, and how does it interact with the new paper-trail regime? (round 11: former Fenegosida head admits \"partial demand is met by such illegally trafficked gold\"; customs loses Rs 520,000/kilo; ~15 kg/day official import limit)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Ask jewelers where they source; impossible to verify directly — triangulate via seizure frequency vs. declared import volumes",
    stakes: "The state's demand for counter-level paperwork (D50) meets an upstream the jeweler cannot document — the compliance gap is structural, not behavioral",
    round: 11,
  },
  {
    id: "D53",
    question: "Is organized retail actually displacing family sunchaandi shops in the Valley, or is the \"consolidation\" narrative ahead of reality? (round 11: indexbox 2026 claims hallmarking/AML costs are \"accelerating consolidation\"; branded showrooms take 15–35% markups with buyback guarantees — productizing the informal counter's trust assets)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Shutter counts on a jewelry lane over 2 years; ask 3 family jewelers if a branded showroom opened near them and what changed",
    stakes: "Decides whether the family shop's moat (community trust, thin margins) holds against certified-purity + guaranteed-buyback — or whether trust-as-a-product wins",
    round: 11,
  },
  {
    id: "D54",
    question: "Does the >80% Indian-karigar labor dependence give goldsmiths bargaining power at festival peaks, and what happens to small shops if the flow shifts? (round 11: 2015 quake precedent — 75% fled, shops couldn't make jewelry)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Ask 2 jewelers: \"who makes your pieces, and what happens when they're not here?\" + watch for karigar wage mentions in trade press",
    stakes: "The making capacity of the whole trade sits in another country's citizens — a labor-supply single point of failure no round had named",
    round: 11,
  },
  {
    id: "D55",
    question: "What share of a counter's net margin does rent actually consume, across trades? (round 12: kirana ~4% of turnover, clothing ~4.6%; with 5–10% net margins ⇒ roughly half the net margin; needs real ledgers, not asks)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "In the five conversations: \"When the month ends and the till is short, who gets paid first — the landlord, the supplier, or the bank?\"",
    stakes: "If rent ≈ half the net margin, the landlord is the counter's largest single cost of *existence* — and Hami's \"thin wallet\" persona thesis gets a concrete ceiling",
    round: 12,
  },
  {
    id: "D56",
    question: "Is advance rent (अग्रिम भाडा) a de facto entry fee — and is it ever returned? (round 12: lease samples show quarterly-in-advance + 3 months at signing; tenants borrow to pay it)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Ask 3 tenants: \"how much advance did you pay, and when you left, what came back?\" + check Civil Code deposit rules in practice",
    stakes: "Advance rent is the merchant's first loan — to the landlord. The scale of the entry cost decides how high the failure threshold is",
    round: 12,
  },
  {
    id: "D57",
    question: "Is the shutter-churn re-pricing cycle measurable — do re-let rents actually exceed the failed tenant's rent? (round 12: onlinepana Sept 2026 reports the freed shutter is re-let \"at a higher price\")",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Two-point asks on a shutter lane: current ask vs. previous tenant's rent (via brokers/associations)",
    stakes: "If every vacancy is an upward repricing, the shutter market has a built-in ratchet that selects for failure — a structural filter no round had named",
    round: 12,
  },
  {
    id: "D58",
    question: "What share of shutter closures convert to foreign migration vs. reopening elsewhere? (round 12: 2023 Baneshwor snapshot — 25–30% closures, ~50% of those migrated; needs a 2026 refresh)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Manpower-agency intake data + association closure counts; ask: \"when the shop closed, where did you go?\"",
    stakes: "The conveyor shutter→migration→remittance→next shop closes the loop between the landlord economy, the manpower economy, and round 8's remittance-funded demand",
    round: 12,
  },
  {
    id: "D59",
    question: "Does KMC's mandatory rental-property registration (FY 2083/84) and 10% commercial rent tax get passed through to tenants? (round 12: the landlord is being papered now, decades after the tenant)",
    state: "unknown",
    stateNote: "UNKNOWN",
    cheapestTest: "Watch KMC rental registration uptake + ask landlords if rent moved after registration",
    stakes: "The formalization wave meets the other side of the counter — whether paperwork lands on the tenant decides if round 2's wall is about to get a second floor",
    round: 12,
  },
];

export const unknownsCount = discoveryUnknowns.length;
