/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GroupRouteImport } from './routes/group'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as RequestRouteImport } from './routes/request'
import { Route as RequestAProjectRouteImport } from './routes/request-a-project'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as VenturesRouteImport } from './routes/ventures'
import { Route as GroupIndexRouteImport } from './routes/group.index'
import { Route as GroupBusinessesRouteImport } from './routes/group.businesses'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupRoute = GroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAProjectRoute = RequestAProjectRouteImport.update({
  id: '/request-a-project',
  path: '/request-a-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const VenturesRoute = VenturesRouteImport.update({
  id: '/ventures',
  path: '/ventures',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIndexRoute = GroupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupRoute,
} as any)
const GroupBusinessesRoute = GroupBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => GroupRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/group': typeof GroupRouteWithChildren
  '/operations': typeof OperationsRoute
  '/process': typeof ProcessRoute
  '/request': typeof RequestRoute
  '/request-a-project': typeof RequestAProjectRoute
  '/services': typeof ServicesRouteWithChildren
  '/technology': typeof TechnologyRoute
  '/ventures': typeof VenturesRoute
  '/group/businesses': typeof GroupBusinessesRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/group/': typeof GroupIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/operations': typeof OperationsRoute
  '/process': typeof ProcessRoute
  '/request': typeof RequestRoute
  '/request-a-project': typeof RequestAProjectRoute
  '/technology': typeof TechnologyRoute
  '/ventures': typeof VenturesRoute
  '/group/businesses': typeof GroupBusinessesRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/group': typeof GroupIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/group': typeof GroupRouteWithChildren
  '/operations': typeof OperationsRoute
  '/process': typeof ProcessRoute
  '/request': typeof RequestRoute
  '/request-a-project': typeof RequestAProjectRoute
  '/services': typeof ServicesRouteWithChildren
  '/technology': typeof TechnologyRoute
  '/ventures': typeof VenturesRoute
  '/group/businesses': typeof GroupBusinessesRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/group/': typeof GroupIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/group'
    | '/operations'
    | '/process'
    | '/request'
    | '/request-a-project'
    | '/services'
    | '/technology'
    | '/ventures'
    | '/group/businesses'
    | '/services/$slug'
    | '/group/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/operations'
    | '/process'
    | '/request'
    | '/request-a-project'
    | '/technology'
    | '/ventures'
    | '/group/businesses'
    | '/services/$slug'
    | '/group'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/group'
    | '/operations'
    | '/process'
    | '/request'
    | '/request-a-project'
    | '/services'
    | '/technology'
    | '/ventures'
    | '/group/businesses'
    | '/services/$slug'
    | '/group/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GroupRoute: typeof GroupRouteWithChildren
  OperationsRoute: typeof OperationsRoute
  ProcessRoute: typeof ProcessRoute
  RequestRoute: typeof RequestRoute
  RequestAProjectRoute: typeof RequestAProjectRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TechnologyRoute: typeof TechnologyRoute
  VenturesRoute: typeof VenturesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group': {
      id: '/group'
      path: '/group'
      fullPath: '/group'
      preLoaderRoute: typeof GroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-a-project': {
      id: '/request-a-project'
      path: '/request-a-project'
      fullPath: '/request-a-project'
      preLoaderRoute: typeof RequestAProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventures': {
      id: '/ventures'
      path: '/ventures'
      fullPath: '/ventures'
      preLoaderRoute: typeof VenturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/': {
      id: '/group/'
      path: '/'
      fullPath: '/group/'
      preLoaderRoute: typeof GroupIndexRouteImport
      parentRoute: typeof GroupRoute
    }
    '/group/businesses': {
      id: '/group/businesses'
      path: '/businesses'
      fullPath: '/group/businesses'
      preLoaderRoute: typeof GroupBusinessesRouteImport
      parentRoute: typeof GroupRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface GroupRouteChildren {
  GroupBusinessesRoute: typeof GroupBusinessesRoute
  GroupIndexRoute: typeof GroupIndexRoute
}

const GroupRouteChildren: GroupRouteChildren = {
  GroupBusinessesRoute: GroupBusinessesRoute,
  GroupIndexRoute: GroupIndexRoute,
}

const GroupRouteWithChildren = GroupRoute._addFileChildren(GroupRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GroupRoute: GroupRouteWithChildren,
  OperationsRoute: OperationsRoute,
  ProcessRoute: ProcessRoute,
  RequestRoute: RequestRoute,
  RequestAProjectRoute: RequestAProjectRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TechnologyRoute: TechnologyRoute,
  VenturesRoute: VenturesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
