/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as BotQualificationDemoRouteImport } from './routes/bot-qualification-demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DiscoveriesRouteImport } from './routes/discoveries'
import { Route as DomainRouteImport } from './routes/domain'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ForgeBotIntakeRouteImport } from './routes/forge-bot-intake'
import { Route as GroupRouteImport } from './routes/group'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as RequestRouteImport } from './routes/request'
import { Route as RequestAProjectRouteImport } from './routes/request-a-project'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SystemRouteImport } from './routes/system'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as VenturesRouteImport } from './routes/ventures'
import { Route as WorkRouteImport } from './routes/work'
import { Route as GroupIndexRouteImport } from './routes/group.index'
import { Route as GroupBusinessesRouteImport } from './routes/group.businesses'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const BotQualificationDemoRoute = BotQualificationDemoRouteImport.update({
  id: '/bot-qualification-demo',
  path: '/bot-qualification-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveriesRoute = DiscoveriesRouteImport.update({
  id: '/discoveries',
  path: '/discoveries',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainRoute = DomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeBotIntakeRoute = ForgeBotIntakeRouteImport.update({
  id: '/forge-bot-intake',
  path: '/forge-bot-intake',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupRoute = GroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAProjectRoute = RequestAProjectRouteImport.update({
  id: '/request-a-project',
  path: '/request-a-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const VenturesRoute = VenturesRouteImport.update({
  id: '/ventures',
  path: '/ventures',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIndexRoute = GroupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupRoute,
} as any)
const GroupBusinessesRoute = GroupBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => GroupRoute,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/actions': typeof ActionsRoute
  '/bot-qualification-demo': typeof BotQualificationDemoRoute
  '/contact': typeof ContactRoute
  '/discoveries': typeof DiscoveriesRoute
  '/domain': typeof DomainRoute
  '/feed': typeof FeedRoute
  '/forge-bot-intake': typeof ForgeBotIntakeRoute
  '/group': typeof GroupRouteWithChildren
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/owner': typeof OwnerRoute
  '/process': typeof ProcessRoute
  '/providers': typeof ProvidersRoute
  '/request': typeof RequestRoute
  '/request-a-project': typeof RequestAProjectRoute
  '/services': typeof ServicesRouteWithChildren
  '/system': typeof SystemRoute
  '/technology': typeof TechnologyRoute
  '/ventures': typeof VenturesRoute
  '/work': typeof WorkRoute
  '/group/businesses': typeof GroupBusinessesRoute
  '/requests/$id': typeof RequestsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/group/': typeof GroupIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/actions': typeof ActionsRoute
  '/bot-qualification-demo': typeof BotQualificationDemoRoute
  '/contact': typeof ContactRoute
  '/discoveries': typeof DiscoveriesRoute
  '/domain': typeof DomainRoute
  '/feed': typeof FeedRoute
  '/forge-bot-intake': typeof ForgeBotIntakeRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/owner': typeof OwnerRoute
  '/process': typeof ProcessRoute
  '/providers': typeof ProvidersRoute
  '/request': typeof RequestRoute
  '/request-a-project': typeof RequestAProjectRoute
  '/system': typeof SystemRoute
  '/technology': typeof TechnologyRoute
  '/ventures': typeof VenturesRoute
  '/work': typeof WorkRoute
  '/group/businesses': typeof GroupBusinessesRoute
  '/requests/$id': typeof RequestsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/group': typeof GroupIndexRoute
  '/services': typeof ServicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/actions': typeof ActionsRoute
  '/bot-qualification-demo': typeof BotQualificationDemoRoute
  '/contact': typeof ContactRoute
  '/discoveries': typeof DiscoveriesRoute
  '/domain': typeof DomainRoute
  '/feed': typeof FeedRoute
  '/forge-bot-intake': typeof ForgeBotIntakeRoute
  '/group': typeof GroupRouteWithChildren
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/owner': typeof OwnerRoute
  '/process': typeof ProcessRoute
  '/providers': typeof ProvidersRoute
  '/request': typeof RequestRoute
  '/request-a-project': typeof RequestAProjectRoute
  '/services': typeof ServicesRouteWithChildren
  '/system': typeof SystemRoute
  '/technology': typeof TechnologyRoute
  '/ventures': typeof VenturesRoute
  '/work': typeof WorkRoute
  '/group/businesses': typeof GroupBusinessesRoute
  '/requests/$id': typeof RequestsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/group/': typeof GroupIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/actions'
    | '/bot-qualification-demo'
    | '/contact'
    | '/discoveries'
    | '/domain'
    | '/feed'
    | '/forge-bot-intake'
    | '/group'
    | '/login'
    | '/operations'
    | '/opportunities'
    | '/owner'
    | '/process'
    | '/providers'
    | '/request'
    | '/request-a-project'
    | '/services'
    | '/system'
    | '/technology'
    | '/ventures'
    | '/work'
    | '/group/businesses'
    | '/requests/$id'
    | '/services/$slug'
    | '/group/'
    | '/services/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/actions'
    | '/bot-qualification-demo'
    | '/contact'
    | '/discoveries'
    | '/domain'
    | '/feed'
    | '/forge-bot-intake'
    | '/login'
    | '/operations'
    | '/opportunities'
    | '/owner'
    | '/process'
    | '/providers'
    | '/request'
    | '/request-a-project'
    | '/system'
    | '/technology'
    | '/ventures'
    | '/work'
    | '/group/businesses'
    | '/requests/$id'
    | '/services/$slug'
    | '/group'
    | '/services'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/actions'
    | '/bot-qualification-demo'
    | '/contact'
    | '/discoveries'
    | '/domain'
    | '/feed'
    | '/forge-bot-intake'
    | '/group'
    | '/login'
    | '/operations'
    | '/opportunities'
    | '/owner'
    | '/process'
    | '/providers'
    | '/request'
    | '/request-a-project'
    | '/services'
    | '/system'
    | '/technology'
    | '/ventures'
    | '/work'
    | '/group/businesses'
    | '/requests/$id'
    | '/services/$slug'
    | '/group/'
    | '/services/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ActionsRoute: typeof ActionsRoute
  BotQualificationDemoRoute: typeof BotQualificationDemoRoute
  ContactRoute: typeof ContactRoute
  DiscoveriesRoute: typeof DiscoveriesRoute
  DomainRoute: typeof DomainRoute
  FeedRoute: typeof FeedRoute
  ForgeBotIntakeRoute: typeof ForgeBotIntakeRoute
  GroupRoute: typeof GroupRouteWithChildren
  LoginRoute: typeof LoginRoute
  OperationsRoute: typeof OperationsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  OwnerRoute: typeof OwnerRoute
  ProcessRoute: typeof ProcessRoute
  ProvidersRoute: typeof ProvidersRoute
  RequestRoute: typeof RequestRoute
  RequestAProjectRoute: typeof RequestAProjectRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SystemRoute: typeof SystemRoute
  TechnologyRoute: typeof TechnologyRoute
  VenturesRoute: typeof VenturesRoute
  WorkRoute: typeof WorkRoute
  RequestsIdRoute: typeof RequestsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-qualification-demo': {
      id: '/bot-qualification-demo'
      path: '/bot-qualification-demo'
      fullPath: '/bot-qualification-demo'
      preLoaderRoute: typeof BotQualificationDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discoveries': {
      id: '/discoveries'
      path: '/discoveries'
      fullPath: '/discoveries'
      preLoaderRoute: typeof DiscoveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain': {
      id: '/domain'
      path: '/domain'
      fullPath: '/domain'
      preLoaderRoute: typeof DomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge-bot-intake': {
      id: '/forge-bot-intake'
      path: '/forge-bot-intake'
      fullPath: '/forge-bot-intake'
      preLoaderRoute: typeof ForgeBotIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group': {
      id: '/group'
      path: '/group'
      fullPath: '/group'
      preLoaderRoute: typeof GroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-a-project': {
      id: '/request-a-project'
      path: '/request-a-project'
      fullPath: '/request-a-project'
      preLoaderRoute: typeof RequestAProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventures': {
      id: '/ventures'
      path: '/ventures'
      fullPath: '/ventures'
      preLoaderRoute: typeof VenturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/': {
      id: '/group/'
      path: '/'
      fullPath: '/group/'
      preLoaderRoute: typeof GroupIndexRouteImport
      parentRoute: typeof GroupRoute
    }
    '/group/businesses': {
      id: '/group/businesses'
      path: '/businesses'
      fullPath: '/group/businesses'
      preLoaderRoute: typeof GroupBusinessesRouteImport
      parentRoute: typeof GroupRoute
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GroupRouteChildren {
  GroupBusinessesRoute: typeof GroupBusinessesRoute
  GroupIndexRoute: typeof GroupIndexRoute
}

const GroupRouteChildren: GroupRouteChildren = {
  GroupBusinessesRoute: GroupBusinessesRoute,
  GroupIndexRoute: GroupIndexRoute,
}

const GroupRouteWithChildren = GroupRoute._addFileChildren(GroupRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ActionsRoute: ActionsRoute,
  BotQualificationDemoRoute: BotQualificationDemoRoute,
  ContactRoute: ContactRoute,
  DiscoveriesRoute: DiscoveriesRoute,
  DomainRoute: DomainRoute,
  FeedRoute: FeedRoute,
  ForgeBotIntakeRoute: ForgeBotIntakeRoute,
  GroupRoute: GroupRouteWithChildren,
  LoginRoute: LoginRoute,
  OperationsRoute: OperationsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  OwnerRoute: OwnerRoute,
  ProcessRoute: ProcessRoute,
  ProvidersRoute: ProvidersRoute,
  RequestRoute: RequestRoute,
  RequestAProjectRoute: RequestAProjectRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SystemRoute: SystemRoute,
  TechnologyRoute: TechnologyRoute,
  VenturesRoute: VenturesRoute,
  WorkRoute: WorkRoute,
  RequestsIdRoute: RequestsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
